.only-default: &only-default
  only:
    - master
    - merge_requests
    - tags

print_merge:
  script:
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_SHA
  only:
    - merge_requests

print_nonmerge:
  script:
    - echo $CI_COMMIT_BEFORE_SHA
  except:
    - merge_requests

ci_secrets:
  <<: *only-default
  image: python:stretch
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/pmarlow/ci_secrets /tmp/ci_secrets
    - pip install -e /tmp/ci_secrets
  script:
    # Pass in SHA based on whether this is a merge or not"
    - export SINCE_SHA="${CI_MERGE_REQUEST_TARGET_BRANCH_SHA:-$CI_COMMIT_BEFORE_SHA}"
    - ci_secrets --since $SINCE_SHA
