before_script:
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/pmarlow/ci_secrets /tmp/ci_secrets
  - pip install -e /tmp/ci_secrets

ci_secrets:
  image: python:stretch
  script:
    - ci_secrets --since $CI_COMMIT_BEFORE_SHA
